name = "Clarity"
license = "MIT"
licenselink = "https://github.com/chipzoller/hugo-clarity/blob/master/LICENSE.md"
description = "Este taller está dirigido a usuarios de R que han tenido un acercamiento con el análisis espacial de datos dentro de QGIS (Software de Sistema de Información Geográfica libre y de código abierto) o viceversa. El objetivo es demostrar la utilidad y los beneficios que trae la interoperabilidad de R y QGIS para el trabajo de datos geográficos de forma computacional (geocomputación), ya sea desde automatizar geoprocesos, realizar análisis estadísticos, hasta crear y agregar tus propias herramientas con sus respectivas documentaciones y ejemplos reproducibles."
homepage = "https://github.com/chipzoller/hugo-clarity"
tags = ["blog", "technical", "simple", "dark", "syntax highlighting"]
features = ["blog", "technical", "simple", "dark", "syntax highlighting"]
min_version = "0.63.0"

# If the theme has multiple authors
authors = [
  {name = "Chip Zoller", homepage = "https://neonmirrors.net"},
  {name = "Dan Weru", homepage = "https://github.com/onweru"},
]
