[[main]]
  name = "Home"
  url = "/"
  weight = -111

[[main]]
  name = "Installation"
  url = "installation"
  weight = -110

[[main]]
  name = "Processing R Provider"
  url = "installation"
  weight = 1
  parent = "Installation"

[[main]]
  name = "Dependencies"
  url = "requerimientos"
  weight = 2
  parent = "Installation"
  
[[main]]
  name = "Extras"
  url = "extras"
  weight = -108

[[main]]
  name = "Qgis resource sharing"
  url = "extras"
  weight = 1
  parent = "Extras"
  
[[main]]
  name = "Sharing repository"
  url = "repositorio"
  weight = 2
  parent = "Extras"

[[main]]
  name = "About"
  url = "about/"
  weight = -107
  
# social menu links

[[social]]
  name = "youtube"
  type = "social"
  weight = 1
  url = "https://www.youtube.com/channel/UCkeTQO_SO8tCJNENKS5NnWA"
[[social]]
  name = "telegram"
  weight = 2
  url = "https://t.me/rspatial_es"

[[social]]
  name = "gitlab"
  weight = 4
  url = "https://gitlab.com/rspatial_es"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
